#!/bin/bash

echo "🔍 ДИАГНОСТИКА БЕСПЛАТНОГО УРОВНЯ GCP"
echo "====================================="

echo ""
echo "📋 ЧЕКЛИСТ для Always Free Tier:"
echo ""
echo "✅ 1. РЕГИОН должен быть:"
echo "   - us-west1 (Oregon)"  
echo "   - us-central1 (Iowa)"
echo "   - us-east1 (South Carolina)"
echo "   ❌ НЕ europe-west1, НЕ asia-southeast1!"
echo ""
echo "✅ 2. ЗОНА должна быть:"
echo "   - us-west1-a, us-west1-b, us-west1-c"
echo "   - us-central1-a, us-central1-b, us-central1-c"  
echo "   - us-east1-a, us-east1-b, us-east1-c"
echo ""
echo "✅ 3. MACHINE TYPE должен быть:"
echo "   - ТОЧНО e2-micro (НЕ e2-small, НЕ e2-medium!)"
echo "   - 1 vCPU, 1 GB memory"
echo ""
echo "✅ 4. BOOT DISK должен быть:"
echo "   - Standard persistent disk (НЕ SSD!)"
echo "   - Максимум 30 GB"
echo "   - Ubuntu 22.04 LTS"
echo ""
echo "✅ 5. FIREWALL:"
echo "   - Allow HTTP traffic: можно включить"
echo "   - Allow HTTPS traffic: можно включить"
echo ""
echo "❌ ЧАСТЫЕ ОШИБКИ:"
echo "   - Выбрали европейский регион"
echo "   - Выбрали SSD persistent disk вместо Standard"
echo "   - Диск больше 30GB"
echo "   - Machine type больше e2-micro"
echo "   - Не активирован Free Trial (нужна карта)"
echo ""
echo "🔧 ПОШАГОВАЯ ПРОВЕРКА:"
echo "1. Region: Выберите us-west1"
echo "2. Zone: Выберите us-west1-b"  
echo "3. Machine family: General-purpose"
echo "4. Series: E2"
echo "5. Machine type: e2-micro (1 vCPU, 1 GB memory)"
echo "6. Boot disk: Click 'CHANGE'"
echo "   - Operating system: Ubuntu"
echo "   - Version: Ubuntu 22.04 LTS"
echo "   - Boot disk type: Standard persistent disk"
echo "   - Size: 30 GB (максимум для Free Tier)"
echo "7. Firewall: Allow HTTP и HTTPS можно включить"
echo ""
echo "💡 ПРОВЕРЬТЕ СПРАВА ВНИЗУ:"
echo "   Должно быть написано 'Always Free eligible' или '$0.00'"
echo ""
echo "🚨 ЕСЛИ ВСЕ РАВНО ПЛАТНО:"
echo "   1. Проверьте что активирован Free Trial ($300 кредитов)"
echo "   2. Убедитесь что привязана карта"
echo "   3. Возможно достигли лимита Free Tier"
echo "   4. Проверьте биллинг аккаунта"
